apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb
  labels:
    app: deployment-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
