---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-rbac
  namespace: default
rules:
- apiGroups: [ "", "extensions", "apps" ]
  resources: [ "daemonsets", deployments", "endpoints", "ingress", "nodes", "persistentvolumes", "persistentvolumeclaims", "pods", "services", "statefulsets" ]
  verbs: [ "get", "list", "watch"]
- apiGroups: [ "extensions" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-rbac
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: default